baseURL = "http://localhost/"
languageCode = "es"
title = "Inicio"
theme = "PaperMod"

[params]
  ShowReadingTime = false
  ShowToc = false
  ShowBreadCrumbs = false
  defaultTheme = "auto"
  disableThemeToggle = false
  homeInfoParams = false 
  


[menu]
  [[menu.main]]
    name = "Requisitos"
    url = "/requisitos/"
    weight = 1

  [[menu.main]]
    name = "Justificación"
    url = "/justificacion/"
    weight = 2

  [[menu.main]]
    name = "Presupuesto"
    url = "/presupuesto/"
    weight = 3

  [[menu.main]]
    name = "Conclusiones"
    url = "/conclusiones/"
    weight = 4
