baseURL = "http://localhost/"
languageCode = "es"
title = "Trabajo Final Hardware"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowToc = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
  disableThemeToggle = false

  [params.homeInfoParams]
    Title = "Trabajo Final Hardware"
    Content = "Sitio del trabajo integrador de Laboratorio de Hardware - Tecnicatura en Desarrollo de Software"

[menu]
  [[menu.main]]
    name = "Requisitos"
    url = "/requisitos/"
    weight = 1

  [[menu.main]]
    name = "Justificación"
    url = "/justificacion/"
    weight = 2

  [[menu.main]]
    name = "Presupuesto"
    url = "/presupuesto/"
    weight = 3

  [[menu.main]]
    name = "Conclusiones"
    url = "/conclusiones/"
    weight = 4
